name: LiteVote
version: '3.0'
main: ea.foort.litevote.LiteVote
api-version: '1.16'
author: Foort
commands:
  vote:
  startvote:
  stopvote:

permissions:
  litevote.vote:
    default: true
  litevote.admin:
    default: op
